name: Deploy to Vercel

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Vercel Deploy
        run: |
          curl -X POST "https://api.vercel.com/v1/integrations/deploy/prj_ecRciFGNMPBDIgfLbz44xOPWPpbP/RU2YCKUn14?sha=${{ github.sha }}"
